config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  get '/s/:slug', to: 'links#shortRedirect', as: :short
  get '/', to: 'links#new'
  resources :links do
    collection do
      get :shortRedirect 
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
    # owning all of the logic in the method so the UI can be dumb
    # wanting to make sure we can make sure there's a URL
    validates_presence_of :url
    # is there http or https?
    validates :url, format: URI::regexp(%w[http https])
    # is the slug different than what we've seen
    validates_uniqueness_of :slug

    before_validation :generate_slug

    def short
        Rails.application.routes.url_helpers.short_url(slug: self.slug)
    end

    def generate_slug
        self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
        true
    end

    def self.shorten(url, slug = '')
        # return short when URL with that slug was created before
        link = Link.where(url: url, slug: slug).first
        return link.short if link 
          
        # create a new
        link = Link.new(url: url, slug: slug)
        return link.short if link.save
          
        # if slug is taken, try to add random characters
        Link.shorten(url, slug + SecureRandom.uuid[0..2])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy shortRedirect]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  # this method will update the clicked count in the db for the specific shortened url after click to track usage
  # and redirect the user to the url that was shortened 
  def shortRedirect
    @link.increment!(:clicked)
    redirect_to @link.url
  end

  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Short link was successfully created." }
        #asdfas
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:url, :slug, :clicked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Slug</th>
      <th>Clicked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.short %></td>
        <td><%= link.clicked %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Short Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short Url:</strong>
  <%= link_to @link.short, shortRedirect_links_path(:id => @link.id), target: :_blank %>
</p>

<p>
  <strong>Clicked:</strong>
  <%= @link.clicked %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>